### PR TITLE
Prune cipher list, deprecate TLS v1.0

### PR DESCRIPTION
**Pull request by fuhry**
- PCI-DSS mandates disabling support for TLS 1.0 by June 2016
- Trimmed cipher list down to combinations with:
  - KX: ephemeral Diffie-Hellman (elliptic curve and standard)
  - Cipher: AES256, CBC or GCM
  - Hash: SHA-1, SHA-256 or SHA-384 (the former only for compatibility)
- Add Diffie-Hellman 4,096 bit prime with generator 2

### CODE REVIEW

**Comment by fuhry** [comment]
@dbarboza Can you review when you get a chance?

@henriwatson Do you think you can update the nginx part of this? I updated the cipher list, but I'm not sure how to configure DH/ECDH parameters.

**Comment by unlobito** [comment]
@fuhry You shouldn't be providing DH primes as this makes using the number field sieve to break connections easier (see https://weakdh.org). Consider instead providing an OpenSSL command to regenerate primes? (such as `openssl dhparam -out dhparams.pem 2048`)

You can use the [ssl_dhparam](http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_dhparam) option in nginx to configure the parameters used.

**Comment by fuhry** [comment]
@henriwatson I've added a note to the README urging users to generate their own DH parameters. Since this requires some effort (10-15 minutes on a box with dual top-of-the-line Xeons and a lot of activity throwing bits into the entropy pool) I think we'll still include a set here, but with the caveats thoroughly explained. Your thoughts?

**Comment by unlobito** [comment]
@fuhry If we do that, we're just moving the target. Sure, the users of this repo are far and few compared to the common DH primes that are more widely used but it's still the same problem. Since generating primes is a one-off operation, I don't think asking users to wait a while is too ridiculous.

**Pull request merged**
